### ISSUE TITLE
对于该项目整体的运行

### ISSUE THREAD

**Issue by As1mlpe** [Nocturne228/Job_rec_sys_base_knowledge_graph#1]
作者您好，请问您的这个项目具体怎么运行，方便添加一下您的联系方式沟通一下吗。

**Comment by Nocturne228** [comment]
马跃宸
***@***.***





你好，抱歉没有及时回复，这是我们参加比赛的项目，做的比较投机取巧，可能不太符合你预期的效果，这周末有时间我会整理一下文件

在这里大概讲一下思路，就是我们用图数据库neo4j存储现有的企业招聘信息，然后在github上找到了一个使用roberta训练的职位推荐模型，这个模型可以实现命名实体识别提取出简历中的各项信息，比如学历、获奖状况等等，再用一个doc2vec模型进行向量化，最后计算余弦相似度，生成一个查询语句，大概就是这样
如果还有其他问题可以联系QQ：206088020

                       
Original Email
                       
                     

Sender:"pLaNt"< ***@***.*** &gt;;

Sent Time:2024/5/9 11:02

To:"Nocturne228/Job_rec_sys_base_knowledge_graph"< ***@***.*** &gt;;

Cc recipient:"Subscribed"< ***@***.*** &gt;;

Subject:[Nocturne228/Job_rec_sys_base_knowledge_graph] 对于该项目整体的运行 (Issue #1)




 
作者您好，请问您的这个项目具体怎么运行，方便添加一下您的联系方式沟通一下吗。

**Comment by As1mlpe** [comment]
非常抱歉，今天才看到回复，我已经在QQ上给你发送了申请，如果方便的话可以在QQ上详细聊一下。
